### ISSUE TITLE
Latest Beta-8 not launching

### ISSUE THREAD

**Issue by OrangeTheme** [Goldensunboy/WL4Editor#151]
![image](https://user-images.githubusercontent.com/41189379/52949018-0b93c500-3373-11e9-8639-276b2340278c.png)

**Comment by Goldensunboy** [comment]
Is this the mingw or msvc build?

**Comment by Goldensunboy** [comment]
It appears that some binaries are missing from the msvc build, it does not work for me either. ssp will look into fixing it

**Comment by shinespeciall** [comment]
fixed, added LICENSE, CHHANGELOG and plugins folder for MSVC64 build.
