### ISSUE TITLE
Crash when un-doing changes

### ISSUE THREAD

**Issue by OrangeTheme** [Goldensunboy/WL4Editor#152]
N.B. You don't need to change the tile selected, the editor will crash the next time you try to place a tile.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/41189379/53007769-d4371e00-342f-11e9-80e1-7937d600a8f9.gif)

**Comment by shinespeciall** [comment]
confirmed in msvc64 build, will look into it.

**Comment by shinespeciall** [comment]
just update my VS2017 to 15.9.7 and find they fixed several stack corruption and other issues. you can try the next msvc17_64 build and see if it fixed.

**Comment by Goldensunboy** [comment]
Can confirm this is happening in the mingw build, too; it seems like heap corruption
